name             'chef_cleaner'
maintainer       'Vsevolod Polyakov, Grammarly Inc.'
maintainer_email 'ctrlok@gmail.com'
license          'MIT'
description      'This is small handler for clean directories from files not created by chef resources'
long_description 'This is small handler for clean directories from files not created by chef resources'
version          '1.0.2'
